[package]
name = "kestrel"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
coin_cbc = "0.1.7"
egg = "0.9.3"
lang-c = "0.15"
log = "0.4.17"
nom = "7"
regex = "1"
sexp = "1.1.4"